version: '3'

services:
  postgres:
    restart: always
    image: postgres
    container_name: photo_edit_db
  web:
    container_name: photo_edit_web
    build: ./photoedit
    env_file:
      - .env
    volumes:
      - .:/code
    ports: 
      - "8000:8000"
    depends_on:
      - postgres

